stages:
  check_metadata:
    cmd: python src/data/pull_raw_metadata.py
  create_files_table:
    cmd: python src/data/create_files_table.py
    params:
      - create_files_table.last_modified
  create_contents_table:
    cmd: python src/data/create_contents_table.py
    params:
      - create_contents_table.last_modified
